apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: k8s-name-client
  name: k8s-name-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-name-client
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: k8s-name-client
    spec:
      serviceAccountName: spring-cloud
      containers:
      - image: krishnaktg/k8s-name-client
        name: k8s-name-client
#        readinessProbe:
#          httpGet:
#            port: 8080
#            path: /actuator/health/readiness
#        livenessProbe:
#          httpGet:
#            port: 8080
#            path: /actuator/health/liveness
#        lifecycle:
#          preStop:
#            exec:
#              command: ["sh", "-c", "sleep 10"]
#        resources: {}
status: {}
