apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: k8s-name-client
  name: k8s-name-client
spec:
  ports:
  - name: 80-8080
    port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 30008
  selector:
    app: k8s-name-client
  type: NodePort
status:
  loadBalancer: {}
