apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: k8s-boot-probes
  name: k8s-boot-probes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-boot-probes
  strategy: {}
  template:
    metadata:
      labels:
        app: k8s-boot-probes
    spec:
      containers:
        - image: krishnaktg/k8s-boot-probes
          name: k8s-boot-probes
          resources: {}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"]
