apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8s-name-service
  name: k8s-name-service
spec:
  ports:
  - name: 80-8080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: k8s-name-service
  type: ClusterIP
