apiVersion: v1
kind: ConfigMap
metadata:
  #  matches the spring app name as defined in application.yml
  name: k8s-config-reload
data:
  #  must be named 'application.yaml' or be the only key in this config
  #  refer to Spring Cloud Kubernetes Config documentation or source code
  application.yaml: |
    app:
      config: This is a sample config
    bean:
      message: This is coming from Minikube K8s Cluster - version 2.