apiVersion: v1
kind: Service
metadata:
  name: k8s-config-reload-service
  labels:
    name: k8s-config-reload-service
spec:
  selector:
    app: k8s-config-reload
  type: NodePort
  ports:
    - name: springboot
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30008
    
