apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: k8s-name-client
build:
  artifacts:
    - image: krishnaktg/k8s-name-client
      buildpacks:
        builder: gcr.io/paketo-buildpacks/builder:base-platform-api-0.3
        dependencies:
          paths:
            - src
            - pom.xml
deploy:
  kubectl:
    manifests:
    - k8s/security.yaml
    - k8s/deployment.yaml
    - k8s/service.yaml
