spring:
  application:
    name: k8s-config-reload
  cloud:
    kubernetes:
      enabled: true
      config:
        enabled: true
        name: k8s-config-reload
        namespace: default
      reload:
        enabled: true
        mode: event
        strategry: refresh

management:
  server:
    port: 8080
  endpoint:
    restart.enabled : true
    health.enabled : true
    info.enabled : true